# models/interfaces.py
from typing import Protocol, Tuple, Set, List, Optional, Dict


class ReadOnlyBoard(Protocol):
    """Defines only the read-only operations needed by controllers."""
    def get_token(self, row: int, col: int) -> str: ...
    def is_within_bounds(self, row: int, col: int) -> bool: ...
    def is_empty(self, row: int, col: int) -> bool: ...
    @property
    def matrix(self) -> List[List[str]]: ...

class MovementStatus(Protocol):
    """Defines only the state properties needed to validate movement."""
    @property
    def moved_pieces(self) -> Set[Tuple[int, int]]: ...
    @property
    def game_over(self) -> bool: ...
    @property
    def selected_pos(self) -> Tuple[int, int]: ...
    @selected_pos.setter
    def selected_pos(self, value: Optional[Tuple[int, int]]) -> None: ...


class WritableBoard(Protocol):
    def get_token(self, row: int, col: int) -> str: ...

    def set_token(self, row: int, col: int, token: str) -> None: ...

    def clear_cell(self, row: int, col: int) -> None: ...

    @property
    def height(self) -> int: ...


class WritableGameStatus(Protocol):
    @property
    def game_clock_ms(self) -> int: ...

    @game_clock_ms.setter
    def game_clock_ms(self, value: int): ...

    @property
    def game_over(self) -> bool: ...

    @game_over.setter
    def game_over(self, value: bool): ...

    @property
    def pending_movements(self) -> List: ...  # Use specific type if possible

    @pending_movements.setter
    def pending_movements(self, value: List): ...

    @property
    def airborne_pieces(self) -> Dict: ...

    @property
    def moved_pieces(self) -> Set[Tuple[int, int]]: ...

